name: Update GitLab Stats

on:
  schedule:
    - cron: "0 0 * * *"   # Todos los días a medianoche (UTC)
  workflow_dispatch:       # Permite ejecutarlo manualmente también

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install requests cairosvg

      - name: Run script
        env:
          GITLAB_USERNAME: MARAST01
        run: python gitlab-stats.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add gitlab-stats.svg
          git commit -m "Update GitLab Stats" || exit 0
          git push
