name: Update GitLab Stats

on:
  schedule:
    - cron: "0 0 * * *"   # todos los días
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          sed -i "s/GITLAB_TOKEN = \"\"/GITLAB_TOKEN = \"${GITLAB_TOKEN}\"/" gitlab-stats/gitlab_stats.py
          python gitlab-stats/gitlab_stats.py

      - name: Commit and push SVG
        run: |
          git config --global user.name "github-actions-bot"
          git config --global user.email "bot@github.com"
          git add gitlab-stats.svg
          git commit -m "Update GitLab stats" || exit 0
          git push
